### PR TITLE
Move to Docker Compose and Travis CI

### LINKED ISSUE #135: Moving to Docker Compose and Travis CI
#63 explained why we moved from Travis CI to self-hosted Drone CI. Two main reasons were matrix builds and `docker exec` for local testing.

Unfortunately, Drone 0.6 removed ability to run all matrix builds with `drone exec`. https://github.com/drone/drone-cli/issues/49 In addition to that, maintaining my own instance of Drone CI on Scaleway became a problem – while it is relatively cheap and powerful, it has too many issues: I filled way too many support tickets with subject "Server hung in "starting" state".

(Also, I don't want my CI system to be fucked up. 😆 https://github.com/cncd/pipeline/issues/30)

I propose to move testing to Docker Compose and use some duct tape to run tests locally using it.

### PR DESCRIPTION
**Pull request by AlekSi**
Closes #135.

### CODE REVIEW

**Comment by AlekSi** [comment]
@AlekseyMartynov I wonder what it will take to use the same method on Windows?

**Comment by AlekseyMartynov** [comment]
> I wonder what it will take to use the same method on Windows?

With Docker for Windows 17.09, the following commands run fine:

```
mingw32-make deps
mingw32-make test-dc
```

Had to make one adjustoment: replace /tmp/reform-database.sqlite3 with %TEMP%/reform-database.sqlite3 in Makefile

**Comment by AlekSi** [comment]
> Had to make one adjustoment: replace /tmp/reform-database.sqlite3 with %TEMP%/reform-database.sqlite3 in Makefile

Is there a syntax that could work on both Unix and Windows?

**Comment by AlekseyMartynov** [comment]
> Is there a syntax that could work on both Unix and Windows?

A simple option is to put reform-database.sqlite3 into the repo root and also add it to .gitignore

**Comment by AlekSi** [comment]
Unfortunately, that will not work due to `go test` changing the current directory. There will be files: in `reform-db/` with schema and the empty one in the root.

**Comment by AlekseyMartynov** [comment]
`$(CURDIR)/reform-database.sqlite3` - this worked on Windows

**Comment by AlekseyMartynov** [comment]
I forgot one more nuance. I had to copy or symlink `mingw32-make.exe` as `make.exe` because `make` is invoked recursively.

**Pull request merged**
