### PR TITLE
MS SQL

### LINKED ISSUE #33: AppVeyor for Windows builds
* [x] add AppVeyor configuration
* [x] add badge

https://ci.appveyor.com/project/AlekSi/reform

### PR DESCRIPTION
**Pull request by AlekseyMartynov**
Work in progress.

* ~~Build fails due to reasons discused in #11~~
* ~~A temporary hack is used to mask `LIMIT 1` incompatibility (querier_selects.go)~~
* ~~Prabably there are problems with datetime columns, not sure~~

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
I suggest setting "Skip branches without appveyor.yml" in AppVeyor project settings (online) to prevent things like https://ci.appveyor.com/project/AlekSi/reform/build/1.0.4

**Comment by AlekSi** [comment]
> I suggest setting "Skip branches without appveyor.yml" in AppVeyor project settings
Done

May you please make a separate pull request with just `appveyor.yml` which runs basic tests (without databases)? I want to grok every line of it before we move forward, so I can be able to support it in the future.

**Comment by AlekseyMartynov** [comment]
Sure. https://github.com/go-reform/reform/pull/37

**Comment by AlekSi** [comment]
May you please rebase on top of current `v1-stable`?

**Comment by AlekseyMartynov** [comment]
Done

**Comment by AlekSi** [comment]
Integrating it in #45.

@AlekseyMartynov Gopher is yours! Please send me your full postal address by email. And thank you very much!

**Comment by AlekseyMartynov** [comment]
> Gopher is yours!

Oh yes!



Thanks guys!

**Pull request closed without merging**
