### PR TITLE
Add basic AppVeyor config (closes #33)

### LINKED ISSUE #33: AppVeyor for Windows builds
* [x] add AppVeyor configuration
* [x] add badge

https://ci.appveyor.com/project/AlekSi/reform

### PR DESCRIPTION
**Pull request by AlekseyMartynov**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
FYI the effect of caching added in https://github.com/go-reform/reform/pull/37/commits/92b043976884af98b8b934db104148ae2d06a674 will be visible only after merge. Example: https://ci.appveyor.com/project/AlekseyMartynov/reform/build/18, lines 5-7

**Comment by AlekSi** [comment]
Do we really need gcc? Can't we use Visual Studio to build sqlite3 package? Or we may run only SQL Server tests on AppVeyor.

I feel the same about make. I rather use nmake to batch file on Windows than build GNU make.

**Comment by AlekseyMartynov** [comment]
> Do we really need gcc? Can't we use Visual Studio to build sqlite3 package?

It seems so. See

* https://github.com/golang/go/wiki/cgo#windows
* https://github.com/mattn/go-sqlite3/issues/214#issuecomment-144345881

You know, gcc and make don't look native on Windows, fair point. However they allow to have the same local development process regardless of the OS. When I work on reform locally on my Windows machine I use the same `make init`, `make test` commands, and `make test_mattn_go-sqlite3` works too. 

I like that all targets go together in a single file and that there is no duplication of config.

What do you think?

**Comment by AlekSi** [comment]
Makes sense. Pulled into `appveyor` branch, will take another look later today and merge.

Is there a grouping for `if defined`?

**Comment by AlekseyMartynov** [comment]
> Is there a grouping for if defined?

Yep. Two options for this: multiline blocks in YAML or extract all install steps to a batch file. Which one do you like more?

**Comment by AlekSi** [comment]
Multiline blocks.

**Comment by AlekseyMartynov** [comment]
It turns out that everything we need is pre-installed on AppVeyor workers https://www.appveyor.com/docs/installed-software :sunglasses:

**Comment by AlekSi** [comment]
Ok, that pull request become too messy. Can you please make a new one with a single commit?

**Comment by AlekseyMartynov** [comment]
Yes, I can squash. 
It's also possible to [squash on merge](https://help.github.com/articles/about-pull-request-merge-squashing/)

**Comment by AlekSi** [comment]
I know about squashing here, but I wanted to preserve you as an author.
Commit applied, thank you!

**Pull request closed without merging**
