### PR TITLE
MS SQL for Drone CI

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
@AlekSi I'd like to suggest the following solution to MS SQL data duplication:
https://github.com/AlekseyMartynov/reform/commit/7ed5bad417ddf2822d21380dbc7031f103c0d714
Concatenate all test SQL into a single stream.

Do you think this can be added to this PR?

**Comment by AlekSi** [comment]
Great idea. Please add it.

**Comment by AlekSi** [comment]
It broke MySQL 5.7 and 8.0. You can see it locally with `make drone`.

**Comment by AlekseyMartynov** [comment]
MySQL's `sql_mode` ruined all my day 😄
After combining SQL script, I cannot find a way to reliably set it for all engine versions. 

With `SET GLOBAL`, the script fails at parsing double quotes. With both `SET` and `SET GLOBAL`, `reform-db` fails without an error message:

> reform-db: 2016/12/20 23:38:13 Internal tool. Do not use it yet.
reform-db: 2016/12/20 23:38:13
Makefile:35: recipe for target 'test-db' failed
make: *** [test-db] Error 1

I came up with setting `sql_mode` in driver DSN instead, which is probably good because it doesn't change global MySQL vars.

Currently Drone fails only with a transient error: 

> Cloning into '/go/src/golang.org/x/net'...
error: RPC failed; result=56, HTTP code = 200

**Comment by AlekSi** [comment]
Merged. Thanks a lot!

**Pull request merged**
